FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src

# Copy csproj and restore as distinct layers
COPY ["ParMusic.API/ParMusic.API.csproj", "ParMusic.API/"]
COPY ["ParMusic.ML/ParMusic.ML.csproj", "ParMusic.ML/"]
RUN dotnet restore "ParMusic.API/ParMusic.API.csproj"

# Copy everything else and build
COPY . .
WORKDIR "/src/ParMusic.API"
RUN dotnet build "ParMusic.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ParMusic.API.csproj" -c Release -o /app/publish

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ParMusic.API.dll"]